# User config
author: "Caitlin Meyer"
tagline: ""
description: "Hey, I'm Caitlin. I coordinate the general education program and make user-friendly guides, tools and videos that help promote library resources and teach library skills at Yale's Cushing/Whitney Medical Library."
email: "caitlin.e.meyer@gmail.com"
linkedin: "https://www.linkedin.com/caitlinemeyer"
instagram: "https://instagram.com/ctlnmyr"
github: "https://github.com/caitlinmeyer"

# Site config
baseurl: "/pineapple"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
